language: php

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1

sudo: false

before_script:
  - composer update $COMPOSER_FLAGS

script: bin/phpunit

notifications:
  irc: "irc.freenode.org#fsi-open"
